env:
  browser: true
  es6: true
  node: true
extends:
  - 'prettier'
  - 'plugin:vue/essential'
  - 'plugin:@typescript-eslint/eslint-recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - prettier
  - vue
  - '@typescript-eslint'
rules:
  "prettier/prettier": "error"
